=== devsukransinci/OPENER-next-master/assets/datasets/map_feature_collection_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "OSM map feature collection",
  "description": "A list of OSM map feature templates, each with an additional visual and textual representation.",
  "type": "array",
  "items": {
    "type": "object",
    "description": "A map feature template.",
    "required": [ "name", "icon", "osm_tags", "osm_element" ],
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "A label describing this map feature.",
        "type": "string"
      },
      "icon": {
        "description": "The icon name/identifier from the custom icons map.",
        "type": "string"
      },
      "osm_tags": {
        "description": "A map of OSM tags that define this map feature.",
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      },
      "osm_element": {
        "description": "The type of OSM element that builds the foundation of this map feature.",
        "$ref": "#/definitions/osm_element_type"
      }
    }
  },
  "definitions": {
    "osm_element_type": { "enum": ["Node", "OpenWay", "ClosedWay", "Relation"] }
  }
}

=== devsukransinci/OPENER-next-master/assets/datasets/map_feature_collection.json
[
  {
    "name": "Haltestelle ohne Plattform",
    "icon": "stop",
    "osm_tags": {
      "public_transport": "platform"
    },
    "osm_element": "Node"
  },
  {
    "name": "Haltestelle mit Plattform",
    "icon": "platform",
    "osm_tags": {
      "public_transport": "platform"
    },
    "osm_element": "OpenWay"
  },
  {
    "name": "Fahrtkartenverkaufsstelle",
    "icon": "ticket_shop",
    "osm_tags": {
      "shop": "ticket",
      "tickets:public_transport": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Informationsstelle",
    "icon": "information",
    "osm_tags": {
      "tourism": "information",
      "information": "office"
    },
    "osm_element": "Node"
  },
  {
    "name": "Fahrkartenautomat",
    "icon": "ticket_machine",
    "osm_tags": {
      "amenity": "vending_machine",
      "vending": "public_transport_tickets"
    },
    "osm_element": "Node"
  },
  {
    "name": "Parkplatz",
    "icon": "parking",
    "osm_tags": {
      "amenity": "parking"
    },
    "osm_element": "Node"
  },
  {
    "name": "Parkplatz",
    "icon": "parking",
    "osm_tags": {
      "amenity": "parking"
    },
    "osm_element": "ClosedWay"
  },
  {
    "name": "Taxi-Stand",
    "icon": "taxi",
    "osm_tags": {
      "amenity": "taxi"
    },
    "osm_element": "Node"
  },
  {
    "name": "Toiletten",
    "icon": "toilet",
    "osm_tags": {
      "amenity": "toilets"
    },
    "osm_element": "Node"
  },
  {
    "name": "Gepäckschließfächer",
    "icon": "locker",
    "osm_tags": {
      "amenity": "luggage_locker"
    },
    "osm_element": "Node"
  },
  {
    "name": "Gepäcktransport",
    "icon": "trolley",
    "osm_tags": {
      "amenity": "trolley_bay"
    },
    "osm_element": "Node"
  },
  {
    "name": "Informationssäule",
    "icon": "terminal_info",
    "osm_tags": {
      "tourism": "information",
      "information": "terminal"
    },
    "osm_element": "Node"
  },
  {
    "name": "Kombinierte Informations- und Notrufsäule",
    "icon": "terminal",
    "osm_tags": {
      "emergency": "phone",
      "tourism": "information",
      "information": "terminal"
    },
    "osm_element": "Node"
  },
  {
    "name": "Notrufsäule",
    "icon": "terminal_emergency",
    "osm_tags": {
      "emergency": "phone"
    },
    "osm_element": "Node"
  }
]
