=== devsukransinci/OPENER-next-master/assets/datasets/question_catalog_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Question Catalog",
  "description": "A list of questions.",
  "type": "array",
  "items": {
    "type": "object",
    "description": "A question derived from the DELFI catalog.",
    "properties": {
      "id": {
        "description": "The DELFI id this question is derived from.",
        "type": "integer",
        "exclusiveMinimum": 0
      },
      "name": {
        "description": "A short title providing additional context to this question.",
        "type": "string"
      },
      "description": {
        "description": "Details or further information describing this question.",
        "type": "string"
      },
      "image": {
        "description": "A list of image urls that may help to clarify this question.",
        "type": "array",
        "items": {
          "type": "string",
          "format": "uri-reference"
        },
        "minItems": 1
      },
      "question": {
        "description": "The actual question. It should be kept as short as possible while still being comprehensible and independent of the context in which it is asked.",
        "type": "string"
      },
      "input": {
        "type": "object",
        "description": "This holds properties specifying the UI input element and its constraints.",
        "properties": {
          "type": {
            "description": "The value type of the answer. This is closely related to the widget that will be displayed to the end user.",
            "enum": ["Bool", "Number", "String", "List", "Duration", "OpeningHours"]
          },
          "unit": {
            "description": "An optional unit that will be displayed to the user.",
            "type": "string"
          },
          "min": {
            "type": "integer"
          },
          "max": {
            "type": "integer"
          },
          "decimals": {
            "description": "An optional property to specify how many decimals are allowed for type Number.",
            "type": "integer"
          },
          "values": {
            "description": "A map of values with additional information for the user and the corresponding OSM tags.",
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "osm_tags": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "image": {
                  "type": "string",
                  "format": "uri-reference"
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false,
        "required": [ "type", "values" ]
      },
      "conditions": {
        "description": "A list of conditions where one must be met in order to ask this question. (Logical OR)",
        "type": "array",
        "items": {
          "description": "All specified properties must be met in order to evaluate the entire condition as true. (Logical AND)",
          "type": "object",
          "properties": {
            "osm_tags": {
              "type": "object",
              "description": "A key value map of OSM tags that must be met in order to evaluate to true.",
              "additionalProperties": {
                "description": "If this is set to a boolean the corresponding osm tag either needs to exist or not independent of its value. An array means one of the given values must match the tag value.",
                "type": ["string", "boolean", "array"],
                "items": {
                  "type": ["string", "boolean"]
                },
                "minItems": 1
              }
            },
            "osm_element": {
              "description": "A single OSM element or list of elements. An array means one of the given elements must match.",
              "anyOf": [
                {
                  "$ref": "#/definitions/osm_element_type"
                },
                {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/osm_element_type"
                  },
                  "minItems": 1
                }
              ]
            }
          },
          "minProperties": 1,
          "additionalProperties": false
        },
        "minItems": 1
      },
      "osm_element": {
        "description": "The type of OSM Element that should be created along side (required for Version 2).",
        "$ref": "#/definitions/osm_element_type"
      },
      "difficulty": {
        "description": "A number that indicates the difficulty of a question which can be used later to filter questions by different levels. Higher means more difficult.",
        "type": "integer",
        "minimum": 0,
        "maximum": 2
      }
    },
    "additionalProperties": false,
    "required": [ "id", "name", "question", "input", "difficulty" ]
  },
  "definitions": {
    "osm_element_type": { "enum": ["Node", "OpenWay", "ClosedWay", "Relation"] }
  }
}

=== devsukransinci/OPENER-next-master/assets/datasets/question_catalog.json
[
   {
      "id": 1021,
      "name": "Betreiber",
      "question": "Welches Verkehrsunternehmen betreibt die Verkaufsstelle?",
      "input": {
         "type": "String",
         "values": {
            "_default_": {
               "osm_tags": {
                  "operator": "%s"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "shop": "ticket",
               "tickets:public_transport": "yes",
               "operator": false
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1021,
      "name": "Öffnungszeiten",
      "question": "Wann ist diese Fahrkartenverkaufsstelle geöffnet?",
      "input": {
         "type": "OpeningHours",
         "values": {
            "_default_": {
               "osm_tags": {
                  "opening_hours": "%s"
               }
            },
            "false": {
               "osm_tags": {
                  "opening_hours": "24/7"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "shop": "ticket",
               "tickets:public_transport": "yes",
               "opening_hours": false
            }
         }
      ],
      "difficulty": 1
   },
   {
      "id": 1022,
      "name": "Für Rollstuhlfahrer zugänglich",
      "question": "Ist die Verkaufsstelle stufenfrei erreichbar?",
      "description": "Stufenfrei bedeutet, eine Schwelle ist weniger als 3cm hoch.",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "wheelchair": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "wheelchair": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "shop": "ticket",
               "tickets:public_transport": "yes",
               "wheelchair": false
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1031,
      "name": "Betreiber",
      "question": "Welches Verkehrsunternehmen betreibt die Informationsstelle?",
      "input": {
         "type": "String",
         "values": {
            "_default_": {
               "osm_tags": {
                  "operator": "%s"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "tourism": "information",
               "information": "office",
               "operator": false
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1031,
      "name": "Öffnungszeiten",
      "question": "Wann ist diese Informationsstelle geöffnet?",
      "input": {
         "type": "OpeningHours",
         "values": {
            "_default_": {
               "osm_tags": {
                  "opening_hours": "%s"
               }
            },
            "false": {
               "osm_tags": {
                  "opening_hours": "24/7"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "tourism": "information",
               "information": "office",
               "opening_hours": false
            }
         }
      ],
      "difficulty": 1
   },
   {
      "id": 1032,
      "name": "Für Rollstuhlfahrer zugänglich",
      "question": "Ist die Informationsstelle stufenfrei erreichbar?",
      "description": "Stufenfrei bedeutet, eine Schwelle ist weniger als 3cm hoch.",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "wheelchair": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "wheelchair": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "tourism": "information",
               "information": "office",
               "wheelchair": false
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1050,
      "name": "Parkplatz",
      "description": "Öffentliche Parkplätze, die von Reisenden in Anspruch genommen werden können und sich in direkter Zuordnung zur Station befinden. Einzelne Parkplätze am Straßenrand fallen nicht unter diese Definition.",
      "image": [
         "assets/questions/image/1050.png"
      ],
      "question": "Gibt es öffentliche Parkplätze für Reisende?",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "amenity": "parking",
                  "access": "yes"
               }
            },
            "false": {}
         }
      },
      "osm_element": "ClosedWay",
      "difficulty": 1
   },
   {
      "id": 1051,
      "name": "Parkplatzart",
      "question": "Um welche Parkplatzart handelt es sich?",
      "input": {
         "type": "List",
         "values": {
            "surface": {
               "name": "Parkplatz",
               "image": "assets/questions/image/1051a.jpg",
               "osm_tags": {
                  "parking": "surface"
               }
            },
            "underground": {
               "name": "Tiefgarage",
               "image": "assets/questions/image/1051b.jpg",
               "osm_tags": {
                  "parking": "underground"
               }
            },
            "street_side": {
               "name": "Parkbucht",
               "image": "assets/questions/image/1051c.jpg",
               "osm_tags": {
                  "parking": "street_side"
               }
            },
            "multi-storey": {
               "name": "Parkhaus",
               "image": "assets/questions/image/1051d.jpg",
               "osm_tags": {
                  "parking": "multi-storey"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  false
               ]
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1051,
      "name": "Behindertenparkplätze",
      "question": "Gibt es hier gesonderte Parkplätze für beeinträchtigte Personen?",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "capacity:disabled": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "capacity:disabled": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  false
               ],
               "capacity:disabled": false
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1051,
      "name": "Behindertenparkplätze",
      "question": "Wie viele Parkplätze für beeinträchtigte Personen gibt es hier?",
      "input": {
         "type": "Number",
         "decimals": 0,
         "min": 1,
         "values": {
            "_default_": {
               "osm_tags": {
                  "capacity:disabled": "%s"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  false
               ],
               "capacity:disabled": "yes"
            }
         }
      ],
      "difficulty": 0
   },
   {
      "id": 1052,
      "name": "Öffnungszeiten",
      "question": "Wann darf hier geparkt werden?",
      "input": {
         "type": "OpeningHours",
         "values": {
            "_default_": {
               "osm_tags": {
                  "opening_hours": "%s"
               }
            },
            "false": {
               "osm_tags": {
                  "opening_hours": "24/7"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  false
               ],
               "opening_hours": false
            }
         }
      ],
      "difficulty": 1
   },
   {
      "id": 1052,
      "name": "Park+Ride",
      "description": "Park & Ride-Anlagen sind Parkplätze mit Anbindung zu öffentlichen Verkehrsmitteln, die Personen, die in die Innenstädte fahren, ermöglichen, ihr Fahrzeug zu verlassen und für den Rest der Reise auf öffentliche Verkehrsmittel umzusteigen.",
      "image": [
         "assets/questions/image/1052.png"
      ],
      "question": "Ist dies ein Park+Ride-Parkplatz?",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "park_ride": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "park_ride": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  false
               ],
               "park_ride": false
            }
         }
      ],
      "difficulty": 1
   },
   {
      "id": 1052,
      "name": "Aufenthaltsdauer",
      "question": "Wie lange darf hier maximal geparkt werden?",
      "input": {
         "type": "Duration",
         "unit": "d:1,h:1,m:5",
         "values": {
            "_default_": {
               "osm_tags": {
                  "maxstay": "%s"
               }
            },
            "false": {
               "osm_tags": {
                  "maxstay": "no"
               }
            }
         }
      },
      "conditions": [
